### ISSUE TITLE
Adicionar Patrocínio Apoio Realização

### ISSUE THREAD

**Issue by CapanemaDaniel** [pmarcus93/egpm#149]
O único realizador é a FAPAM, então está perfeito como está lá. Gostaria que colocasse na mesma linha da realização APOIO, onde vou colocar algumas empresas. E na linha de baixo, onde está APOIO, trocar para PATROCÍNIO. Obrigado.

**Comment by Lucasmg37** [comment]
@CapanemaDaniel Desenvolvimento iniciado.
@pmarcus93 Service para retorno de realizadores adicionado.
Podemos começar a fazer  design da tela.
Branch hotfix/retorno-realizadores

**Comment by pmarcus93** [comment]
@Lucasmg37 o back end já está categorizando apoiadores e patrocinadores? Posso fazer o front end aqui.

**Comment by pmarcus93** [comment]
@CapanemaDaniel já em produção. Nâo colocamos os patrocínios na mesma linha por questões de responsividade. Podemos conversar depois sobre uma alteração maior no layout.
