### ISSUE TITLE
Botão Inscrição

### ISSUE THREAD

**Issue by CapanemaDaniel** [pmarcus93/egpm#152]
Pessoal, seria possível além daquele botão de ingresso ele aparecer por exemplo em forma de menu... No mobile o botão não aparece...

**Comment by pmarcus93** [comment]
Vamos colocar um botão abaixo da logo principal e alterar o botão flutuante no fim da tela.

**Comment by pmarcus93** [comment]
Resolvido e já em produção. @CapanemaDaniel 
No smartphone o botão foi movido para debaixo da logo, para não cortar os conteúdos.
PR #153
