### ISSUE TITLE
Título Palestras

### ISSUE THREAD

**Issue by CapanemaDaniel** [pmarcus93/egpm#155]
Olá. eu troquei o título de palestras para QUIZZES. O conteúdo está alterando mas o título não. obrigado.

**Comment by pmarcus93** [comment]
Já vamos alterar!

**Comment by pmarcus93** [comment]
Já vamos atualizar!

Em sex., 3 de jan. de 2020 às 10:01, Daniel Oliveira Capanema <
notifications@github.com> escreveu:

**Comment by pmarcus93** [comment]
resolvido no master
